/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package entregafinalsmm;

import java.awt.Color;

/**
 *
 * @author carlos
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jSpinner2 = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jPanel5 = new javax.swing.JPanel();
        jSpinner1 = new javax.swing.JSpinner();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jToggleButton10 = new javax.swing.JToggleButton();
        jToggleButton11 = new javax.swing.JToggleButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(2, 1));

        jPanel2.setMaximumSize(new java.awt.Dimension(700, 100));
        jPanel2.setMinimumSize(new java.awt.Dimension(315, 15));
        jPanel2.setPreferredSize(new java.awt.Dimension(350, 30));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jToggleButton1.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jToggleButton1);
        jToggleButton1.setSelected(true);
        jToggleButton1.setMaximumSize(new java.awt.Dimension(20, 15));
        jToggleButton1.setMinimumSize(new java.awt.Dimension(20, 15));
        jToggleButton1.setPreferredSize(new java.awt.Dimension(20, 15));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jToggleButton1);

        jToggleButton2.setBackground(new java.awt.Color(255, 0, 0));
        buttonGroup1.add(jToggleButton2);
        jToggleButton2.setMaximumSize(new java.awt.Dimension(20, 15));
        jToggleButton2.setMinimumSize(new java.awt.Dimension(20, 15));
        jToggleButton2.setPreferredSize(new java.awt.Dimension(20, 15));
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jToggleButton2);

        jToggleButton3.setBackground(new java.awt.Color(0, 0, 255));
        buttonGroup1.add(jToggleButton3);
        jToggleButton3.setMaximumSize(new java.awt.Dimension(20, 15));
        jToggleButton3.setMinimumSize(new java.awt.Dimension(20, 15));
        jToggleButton3.setPreferredSize(new java.awt.Dimension(20, 15));
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jToggleButton3);

        jToggleButton4.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jToggleButton4);
        jToggleButton4.setMaximumSize(new java.awt.Dimension(20, 15));
        jToggleButton4.setMinimumSize(new java.awt.Dimension(20, 15));
        jToggleButton4.setPreferredSize(new java.awt.Dimension(20, 15));
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jToggleButton4);

        jToggleButton5.setBackground(new java.awt.Color(255, 255, 0));
        buttonGroup1.add(jToggleButton5);
        jToggleButton5.setMaximumSize(new java.awt.Dimension(20, 15));
        jToggleButton5.setMinimumSize(new java.awt.Dimension(20, 15));
        jToggleButton5.setPreferredSize(new java.awt.Dimension(20, 15));
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jToggleButton5);

        jToggleButton6.setBackground(new java.awt.Color(0, 255, 0));
        buttonGroup1.add(jToggleButton6);
        jToggleButton6.setMaximumSize(new java.awt.Dimension(20, 15));
        jToggleButton6.setMinimumSize(new java.awt.Dimension(20, 15));
        jToggleButton6.setPreferredSize(new java.awt.Dimension(20, 15));
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jToggleButton6);

        jPanel2.add(jPanel4, java.awt.BorderLayout.LINE_START);

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(3, 0, 10, 1));
        jSpinner1.setMaximumSize(new java.awt.Dimension(50, 32767));
        jSpinner1.setMinimumSize(new java.awt.Dimension(5, 22));
        jSpinner1.setPreferredSize(new java.awt.Dimension(5, 22));
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });
        jSpinner1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jSpinner1FocusLost(evt);
            }
        });
        jSpinner1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSpinner1MouseClicked(evt);
            }
        });
        jSpinner1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jSpinner1KeyPressed(evt);
            }
        });
        jPanel5.add(jSpinner1);

        jCheckBox1.setLabel("Relleno");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel5.add(jCheckBox1);

        jCheckBox2.setText("Transparecia");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel5.add(jCheckBox2);

        jCheckBox3.setText("Alisar");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jPanel5.add(jCheckBox3);

        jCheckBox4.setText("Mover");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        jPanel5.add(jCheckBox4);

        jPanel2.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Barra de estado:");
        jPanel3.add(jLabel1, java.awt.BorderLayout.LINE_START);

        jPanel1.add(jPanel3);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jDesktopPane2.setPreferredSize(new java.awt.Dimension(848, 375));
        jDesktopPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDesktopPane2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 848, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane2, java.awt.BorderLayout.CENTER);

        jPanel6.setLayout(new java.awt.GridLayout(1, 1));

        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.LINE_AXIS));

        buttonGroup2.add(jToggleButton7);
        jToggleButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/trazo.png"))); // NOI18N
        jToggleButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton7ActionPerformed(evt);
            }
        });
        jPanel8.add(jToggleButton7);

        buttonGroup2.add(jToggleButton8);
        jToggleButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/linea.png"))); // NOI18N
        jToggleButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton8ActionPerformed(evt);
            }
        });
        jPanel8.add(jToggleButton8);

        buttonGroup2.add(jToggleButton9);
        jToggleButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/rectangulo.png"))); // NOI18N
        jToggleButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton9ActionPerformed(evt);
            }
        });
        jPanel8.add(jToggleButton9);

        buttonGroup2.add(jToggleButton10);
        jToggleButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/elipse.png"))); // NOI18N
        jToggleButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton10ActionPerformed(evt);
            }
        });
        jPanel8.add(jToggleButton10);

        buttonGroup2.add(jToggleButton11);
        jToggleButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/curva.png"))); // NOI18N
        jToggleButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton11ActionPerformed(evt);
            }
        });
        jPanel8.add(jToggleButton11);

        jPanel6.add(jPanel8);

        getContentPane().add(jPanel6, java.awt.BorderLayout.PAGE_START);

        jMenu3.setText("File");

        jMenuItem1.setText("Nuevo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        VentanaInterna vi;
        vi = (VentanaInterna)jDesktopPane2.getSelectedFrame();
        if(vi !=null) vi.setColor(Color.BLACK);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        VentanaInterna vi;
        vi = (VentanaInterna)jDesktopPane2.getSelectedFrame();
        if(vi !=null){
            vi.setColor(Color.RED);
            System.out.println("Cambio de color a Rojo");
        }
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        VentanaInterna vi = new VentanaInterna();
        jDesktopPane2.add(vi);
        if(vi !=null) vi.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jToggleButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton7ActionPerformed
        VentanaInterna vi;
        vi = (VentanaInterna)jDesktopPane2.getSelectedFrame();
        if(vi !=null) vi.setTool(Tool.TRAZO);
    }//GEN-LAST:event_jToggleButton7ActionPerformed

    private void jToggleButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton8ActionPerformed
        VentanaInterna vi;
        vi = (VentanaInterna)jDesktopPane2.getSelectedFrame();
        if(vi !=null) vi.setTool(Tool.LINEA);
    }//GEN-LAST:event_jToggleButton8ActionPerformed

    private void jToggleButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton9ActionPerformed
        VentanaInterna vi;
        vi = (VentanaInterna)jDesktopPane2.getSelectedFrame();
        if(vi !=null) vi.setTool(Tool.RECTANGULO);
    }//GEN-LAST:event_jToggleButton9ActionPerformed

    private void jToggleButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton10ActionPerformed
        VentanaInterna vi;
        vi = (VentanaInterna)jDesktopPane2.getSelectedFrame();
        if(vi !=null) vi.setTool(Tool.ELIPSE);
    }//GEN-LAST:event_jToggleButton10ActionPerformed

    private void jToggleButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton11ActionPerformed
        VentanaInterna vi;
        vi = (VentanaInterna)jDesktopPane2.getSelectedFrame();
        if(vi !=null) vi.setTool(Tool.CURVA);
    }//GEN-LAST:event_jToggleButton11ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        VentanaInterna vi;
        vi = (VentanaInterna)jDesktopPane2.getSelectedFrame();
        if(vi !=null) vi.setColor(Color.BLUE);
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        VentanaInterna vi;
        vi = (VentanaInterna)jDesktopPane2.getSelectedFrame();
        if(vi !=null) vi.setColor(Color.WHITE);
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        VentanaInterna vi;
        vi = (VentanaInterna)jDesktopPane2.getSelectedFrame();
        if(vi !=null) vi.setColor(Color.YELLOW);
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        VentanaInterna vi;
        vi = (VentanaInterna)jDesktopPane2.getSelectedFrame();
        if(vi !=null) vi.setColor(Color.GREEN);
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        VentanaInterna vi;
        vi = (VentanaInterna)jDesktopPane2.getSelectedFrame();
        if(vi !=null) vi.setRelleno(!vi.getRelleno());
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jSpinner1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinner1KeyPressed
        //TODO: CAMBIAR GROSOR
    }//GEN-LAST:event_jSpinner1KeyPressed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        VentanaInterna vi;
        vi = (VentanaInterna)jDesktopPane2.getSelectedFrame();
        if(vi !=null) vi.setTransparencia(!vi.getTransparencia());
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        VentanaInterna vi;
        vi = (VentanaInterna)jDesktopPane2.getSelectedFrame();
        if(vi !=null) vi.setSuavizado(!vi.getSuavizado());
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jSpinner1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSpinner1MouseClicked
        VentanaInterna vi;
        vi = (VentanaInterna)jDesktopPane2.getSelectedFrame();
        if(vi !=null) vi.setStroke((float)jSpinner1.getValue());
    }//GEN-LAST:event_jSpinner1MouseClicked

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        VentanaInterna vi;
        vi = (VentanaInterna)jDesktopPane2.getSelectedFrame();
        if(vi !=null) vi.setMover(!vi.getMover());
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jSpinner1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jSpinner1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jSpinner1FocusLost

    private void jDesktopPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDesktopPane2MouseClicked
        /*VentanaInterna vi;
        vi = (VentanaInterna)jDesktopPane2.getSelectedFrame();
        if(vi !=null){
            if (vi.getRelleno())
                    
            }
        }*/
    }//GEN-LAST:event_jDesktopPane2MouseClicked

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        VentanaInterna vi;
        vi = (VentanaInterna)jDesktopPane2.getSelectedFrame();
        if(vi !=null) vi.setStroke((Integer)jSpinner1.getValue());
    }//GEN-LAST:event_jSpinner1StateChanged

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    // End of variables declaration//GEN-END:variables
}
